### ISSUE TITLE
Why can't photos with only faces run

### ISSUE THREAD

**Issue by goodlookingbear** [FaceAdapter/Face-Adapter#16]
Hello, sorry to bother you. I don't know much about the code and I just want to run it. It performs well on photos with a collar, but 
photos of the entire face cannot run
IndexError: list index out of range
![19d43677e91ed753e341ff484bd58f7b](https://github.com/FaceAdapter/Face-Adapter/assets/100194514/b8893036-c737-4285-935c-b7e8f27707ec)
![8039f3feeba1b6a318bcb4d5d9465963](https://github.com/FaceAdapter/Face-Adapter/assets/100194514/7db07408-fee2-4900-aedf-0e43874fb72a)

**Comment by 0714lxy0714** [comment]
Hello, may I ask if you are doing direct inference? I am a beginner, and when I followed the author's inst
ructions, I encountered the following error. Could you please help me see what the problem is? Thank you very much!

(posterv2) l@l-ThinkStation-P920:/media/l/56c1a6af-6c26-4b19-8667-59642efbd717/PycharmProjects/Face-Adapter-main$ python infer.py 
2024-07-20 16:39:37.567239: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-20 16:39:37.618005: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-20 16:39:38.285435: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.25it/s]
./checkpoints/third_party/d3dfr_res50_nofc.pth <All keys matched successfully>
<All keys matched successfully>
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'prefer_nhwc': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_max_tuning_duration_ms': '0', 'use_ep_level_unified_stream': '0', 'tunable_op_enable': '0', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'tunable_op_tuning_enable': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_external_alloc': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'has_user_compute_stream': '0', 'gpu_mem_limit': '18446744073709551615', 'device_id': '0'}}
find model: ./checkpoints/third_party/models/antelopev2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'prefer_nhwc': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_max_tuning_duration_ms': '0', 'use_ep_level_unified_stream': '0', 'tunable_op_enable': '0', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'tunable_op_tuning_enable': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_external_alloc': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'has_user_compute_stream': '0', 'gpu_mem_limit': '18446744073709551615', 'device_id': '0'}}
find model: ./checkpoints/third_party/models/antelopev2/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'prefer_nhwc': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_max_tuning_duration_ms': '0', 'use_ep_level_unified_stream': '0', 'tunable_op_enable': '0', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'tunable_op_tuning_enable': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_external_alloc': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'has_user_compute_stream': '0', 'gpu_mem_limit': '18446744073709551615', 'device_id': '0'}}
find model: ./checkpoints/third_party/models/antelopev2/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'prefer_nhwc': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_max_tuning_duration_ms': '0', 'use_ep_level_unified_stream': '0', 'tunable_op_enable': '0', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'tunable_op_tuning_enable': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_external_alloc': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'has_user_compute_stream': '0', 'gpu_mem_limit': '18446744073709551615', 'device_id': '0'}}
find model: ./checkpoints/third_party/models/antelopev2/glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'prefer_nhwc': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_max_tuning_duration_ms': '0', 'use_ep_level_unified_stream': '0', 'tunable_op_enable': '0', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'tunable_op_tuning_enable': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_external_alloc': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'has_user_compute_stream': '0', 'gpu_mem_limit': '18446744073709551615', 'device_id': '0'}}
find model: ./checkpoints/third_party/models/antelopev2/scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
/home/l/anaconda3/envs/posterv2/lib/python3.8/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Traceback (most recent call last):
  File "infer.py", line 297, in <module>
    infer(args)
  File "infer.py", line 214, in infer
    image = pipe(
  File "/home/l/anaconda3/envs/posterv2/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/l/56c1a6af-6c26-4b19-8667-59642efbd717/PycharmProjects/Face-Adapter-main/face_adapter_pipline.py", line 305, in __call__
    self.check_inputs(
  File "/home/l/anaconda3/envs/posterv2/lib/python3.8/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 757, in check_inputs
    raise ValueError(
ValueError: Provide either `ip_adapter_image` or `ip_adapter_image_embeds`. Cannot leave both `ip_adapter_image` and `ip_adapter_image_embeds` defined.

**Comment by tyrink** [comment]
> Hello, sorry to bother you. I don't know much about the code and I just want to run it. It performs well on photos with a collar, but photos of the entire face cannot run IndexError: list index out of range ![19d43677e91ed753e341ff484bd58f7b](https://private-user-images.githubusercontent.com/100194514/347375362-b8893036-c737-4285-935c-b7e8f27707ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTIwMTgsIm5iZiI6MTczMTMxMTcxOCwicGF0aCI6Ii8xMDAxOTQ1MTQvMzQ3Mzc1MzYyLWI4ODkzMDM2LWM3MzctNDI4NS05MzVjLWI3ZThmMjc3MDdlYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNzU1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWU3MGJjODgzNTIzYzhjMzg3YjExODJmNjUwMTQyYmM0MDYyNTM0Y2RmNDFhOTRjZjZmMzkwNDFlYzYxYWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ARYbes8DI8p0JeDIyDfTwZ7vYVbuabTJqnDeo5KGRQE) ![8039f3feeba1b6a318bcb4d5d9465963](https://private-user-images.githubusercontent.com/100194514/347375392-7db07408-fee2-4900-aedf-0e43874fb72a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTIwMTgsIm5iZiI6MTczMTMxMTcxOCwicGF0aCI6Ii8xMDAxOTQ1MTQvMzQ3Mzc1MzkyLTdkYjA3NDA4LWZlZTItNDkwMC1hZWRmLTBlNDM4NzRmYjcyYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNzU1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWYxMzBkMjcwNzYxOTcyYmE0ODZmMWIzZTJiYWFmYzJlMzNkOGYxNjllY2FmMzZiYTJlN2M2ZmE3MjVmNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xFYkHSCbW5zmK5-AXsqCVUCWDULNzBXda4DEQhM1z44)

hi, I have just encountered the same issue and would like to ask if you have any ideas on how to solve it ？

**Comment by m4xig1** [comment]
Hi, if you are using CelebA(-HQ) dataset, you can set 
`app.prepare(ctx_id=0, det_size=(512, 512))`
in line 91. At least it worked for me
